name: matching_donuts
description: "A simple game about matching donuts with the same color"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_riverpod: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  rename_app: ^1.6.1
  riverpod_annotation: ^3.0.0
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.0
  build_runner: ^2.5.4
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/donut-1.png
    - assets/images/donut-2.png
    - assets/images/donut-3.png
    - assets/images/donut-4.png
    - assets/images/donut-5.png
    - assets/images/donut-6.png
    - assets/images/donut-blank.png
    - assets/images/background.png
    - assets/images/blurred-background.png
    - assets/images/health-point.png
    - assets/images/health-point-damaged.png
    - assets/google_fonts/
    - assets/audio/cinema-sins.mp3
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
